apiVersion: 1

datasources:
  - uid: InfluxDB
    name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: pipeline-org
      defaultBucket: aircraft-states
    secureJsonData:
      token: my-super-secret-token
    isDefault: true
    editable: true
